# fly.toml app configuration file generated for events-server on 2023-05-31T05:04:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "events-server"
primary_region = "nrt"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
